### ISSUE TITLE
how to set property

### ISSUE THREAD

**Issue by joyhope** [go-gst/go-gst#110]
I have a pipeline:   h264parse ! nvh264dec ! videoscale ! video/x-raw, width=300, height=800 ! autovideosink, it works.  In the application:  the pipeline is created as：

elems, err := gst.NewElementMany("appsrc", "queue", "h264parse", "nvh264dec", "videoscale",  "appsink")

I try to set videoscale property.  

	//videoscale
	//scale := gst.NewCapsFromString("video/x-raw, width=300, height=800")
	//elems[4].SetProperty("caps",scale)
	//elems[4].Set("caps",scale)
	//elems[4].SetProperty("video/x-raw", "width=300, height=800")
	//elems[4].SetArg("caps","video/x-raw, width=300, height=800")

It seems none of these works.  

How could I set videoscale property?

**Comment by RSWilli** [comment]
This is a general gstreamer question, please use [the official discourse](https://discourse.gstreamer.org/) or the matrix channel for those. Use the go-gst issues for 

Take a look at a [capsfilter](https://gstreamer.freedesktop.org/documentation/coreelements/capsfilter.html?gi-language=c#capsfilter-page) on this element you can force caps. Either you parse your pipeline from string (via `gst.NewPipelineFromString` which works the same as `gst-launch-1.0`) or set the caps on the element manually after constructing them via `gst.NewCapsFromString("video/x-raw, width=300, height=800")`

**Comment by joyhope** [comment]
I  use:  set the caps on the element manually after constructing them via gst.NewCapsFromString("video/x-raw, width=300, height=800")

scale := gst.NewCapsFromString("video/x-raw, width=300, height=800")
//elems[4].SetProperty("caps",scale)
//elems[4].Set("caps",scale)

I tried these two sets, but both did not take action.

**Comment by joyhope** [comment]
Thanks for hint.  elems, err := gst.NewElementMany("appsrc", "queue", "h264parse", "nvh264dec", "videoscale", "capsfilter", "appsink")

scale := gst.NewCapsFromString("video/x-raw, width=300, height=800") is belong to capsfilter, not videoscale. 

Solved.
