### ISSUE TITLE
g_signal_emit_by_name() wrapper function 

### ISSUE THREAD

**Issue by danijelk00** [go-gst/go-gst#115]
I noticed that in Golang, there is a function (*Element) Emit which is a wrapper for g_signal_emitv(). Unfortunately, in my implementation, I need a wrapper for the function g_signal_emit_by_name(), which I cannot find in go-gst. 

Are there any alternatives for this function? I would like to obtain statistics for the rtpbin component.

**Comment by RSWilli** [comment]
The emit function wraps `g_signal_emitv` instead of `g_signal_emit_by_name` for different reasons, but should perform identically AFAIK.

So if you are trying to emit the [`rtpbin::get-internal-session`](https://gstreamer.freedesktop.org/documentation/rtpmanager/rtpbin.html?gi-language=c#rtpbin::get-internal-session) signal the [`Emit`](https://pkg.go.dev/github.com/go-gst/go-glib/glib#Object.Emit) function should be the way to go.

**Comment by danijelk00** [comment]
```
rtpbin.Connect("on-new-ssrc", func(bin *gst.Element, sessionID uint, ssrc uint32) {
		fmt.Printf("New SSRC detected in session %d with SSRC: %d\n", sessionID, ssrc)

		ret, err := rtpbin.Emit("get-internal-session", sessionID)
		
		fmt.Println("Emit successfully called..")

		if err != nil { 
			fmt.Println("error: ", err)
		}
		fmt.Println("Return value:", ret)

	})

```

If i run this code i get the following:

New SSRC detected in session 0 with SSRC: 82655578
Exception 0xc0000028 0x0 0x0 0x7ff8f7e7f90d
PC=0x7ff8f7e7f90d
signal arrived during external code execution

**Comment by RSWilli** [comment]
could you provide a simple reproduction that I can test myself please?

Or debug into the https://github.com/go-gst/go-glib/blob/v1.2.0/glib/gobject.go#L272 function to check where the panic occurs.

**Comment by danijelk00** [comment]
This is code example that i am trying to run on Windows:

```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"strings"
	"time"
	"github.com/go-gst/go-gst/examples"
	"github.com/go-gst/go-gst/gst"
	"github.com/go-gst/go-gst/gst/app"
)

func createPipeline() (*gst.Pipeline, error) {
	gst.Init(nil)

	elements := []string{
		"rtpbin", "name=rtpbin",

		"ksvideosrc", "device-name=\"eMeet Nova\"", "!", "image/jpeg,width=1280,height=720", "!", "jpegdec", "!", "videoconvert", "!", "queue", "!",
		"x264enc", "bframes=0", "speed-preset=ultrafast", "tune=zerolatency","name=encoder", "!", "queue", "!", "rtph264pay", "config-interval=1", "!", "rtpbin.send_rtp_sink_0", "rtpbin.send_rtp_src_0", "!",
		
		"udpsink", "host=127.0.0.1", "port=5510", "sync=false", "async=false", "rtpbin.send_rtcp_src_0", "!",
		
		"udpsink", "host=127.0.0.1", "port=5511", "sync=false", "async=false",
		
		"udpsrc", "port=5511", "caps=\"application/x-rtcp\"", "!", "rtpbin.recv_rtcp_sink_0",
	}

	pipeline, err := gst.NewPipelineFromString(strings.Join(elements, " "))
	if err != nil {
		fmt.Println(err)
	}

	rtpbin, err := pipeline.GetElementByName("rtpbin")
	if err != nil {
		fmt.Println("ERROR: ", err)
	}

	fmt.Println("Rtpbin: ", *rtpbin)

	rtpbin.Connect("on-new-ssrc", func(bin *gst.Element, sessionID uint, ssrc uint32) {
		fmt.Printf("New SSRC detected in session %d with SSRC: %d\n", sessionID, ssrc)

		ret, err := rtpbin.Emit("get-internal-session", sessionID)

		fmt.Println("Emit successfully called..")

		if err != nil {
			fmt.Println("error: ", err)
		}

		fmt.Println("Return value:", ret)

	})
	return pipeline, nil
}

func handleMessage(msg *gst.Message) error {

	switch msg.Type() {
	case gst.MessageEOS:
		return app.ErrEOS
	case gst.MessageError:
		return msg.ParseError()
	}

	return nil
}

func mainLoop(pipeline *gst.Pipeline) error {

	// Start the pipeline
	pipeline.SetState(gst.StatePlaying)

	// Retrieve the bus from the pipeline
	bus := pipeline.GetPipelineBus()

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		pipeline.SendEvent(gst.NewEOSEvent())
	}()

	// Loop over messsages from the pipeline
	for {
		msg := bus.TimedPop(gst.ClockTimeNone)
		if msg == nil {
			break
		}
		if err := handleMessage(msg); err != nil {
			return err
		}
	}

	return nil
}

func main() {

	go func() {
		examples.Run(func() error {
			var pipeline *gst.Pipeline
			var err error
			if pipeline, err = createPipeline(); err != nil {
				return err
			}
			return mainLoop(pipeline)
		})
	}()

	time.Sleep(1 * time.Hour)
}
```

**Comment by RSWilli** [comment]
I had to tweak you code a little because `ksvideosrc` isn't available on linux.

I don't get a panic, but Emit returns an error "invalid GValue". It seems like the type is not correctly set after the signal. I currently don't know why, gotta investigate further.

**Comment by danijelk00** [comment]
Yes, you can use videotestsrc instead of ksvideosrc.

_"Emit() returns an interface{} which must be type asserted as the Go equivalent type to the return value for native C callback."_
~ this could be the reason for "invalid GValue"

On Linux it works fine, but on Windows i have problems

**Comment by RSWilli** [comment]
> this could be the reason for "invalid GValue"

no it isn't. The C call returned a zeroed GValue for me, which most probably means that the C call is wrong somehow.

> On Linux it works fine, but on Windows i have problems

Interesting, I cannot get it to run in Linux. Do those systems have other differences, e.g. in the gstreamer version used?

**Comment by RSWilli** [comment]
@danijelk00 I found the reason, I will create a PRs fo go-glib and go-gst shortly.

I also changed the docs to be less confusing I hope

**Comment by RSWilli** [comment]
Will be available in go-gst after https://github.com/go-gst/go-gst/pull/116

**Comment by danijelk00** [comment]
@RSWilli 

Great, I’m glad you managed to get it working!

On Linux, I tried two different approaches:

- Using the go-gst function Emit, I got a pointer to RTPSession, while on Windows, that step wasn’t possible (I was getting an error).

- Using cgo and implementing C code within Golang code, I managed to call the g_signal_emit_by_name function and extract the GstStructure "stats," which was my goal. (Unfortunately, this implementation is a bit more complicated for Windows, so directly using the Emit function would be much simpler.)

Thank you very much for your help, and I will test if the function works once you finish the changes!

**Comment by RSWilli** [comment]
@danijelk00 

you can already test it if you reference the branches via replace. To be sure I added a test in go-gst: https://github.com/go-gst/go-gst/blob/682a4b03d75f50abaf63da6834f33dc6df7dfbb0/gst/gst_element_emit_test.go#L68

**Comment by danijelk00** [comment]
@RSWilli 

I tried running the code with "go run main.go" , but I'm still getting an exit status. 

However, I noticed something strange: 
- when I run the code using the debugger (vs code debugger or dlv debug) , everything seems to work fine, and I successfully print the values returned by the GetProperty function. 

<img width="770" alt="dlv" src="https://github.com/user-attachments/assets/4c2bbac7-fe60-4291-8d75-03358a383ed6">



What could be the reason? I'm using version 1.2.1 for both go-gst and go-glib.

When running with gdb i got following:
<img width="721" alt="gdb" src="https://github.com/user-attachments/assets/0736b48b-f9c7-4f03-a156-d88902dfbf28">

**Comment by RSWilli** [comment]
I think it may be that the GC is cleaning up the object while you still need the `GstStructure`. Hard to tell though without the code.

I suggest that you unmarshal the structure into a go object with `Structure.UnmarshalInto()` and maybe a `runtime.Keepallive()` of the object. If the problem persists, please create a new issue
