### ISSUE TITLE
Is there a way to statically compile Go plugins with gstreamer?

### ISSUE THREAD

**Issue by iameli-streams** [go-gst/go-gst#136]
Hi! Love the project, using it extensively at Aquareum.

[The gofilesink example shows how to create a dynamically linked library using `go build -o c-shared`.](https://github.com/go-gst/go-gst/blob/7bc995c4f5783470255577bdd9c1c888989f486c/examples/plugins/gofilesink/filesink.go#L14) But I'm working with a project that has gstreamer statically linked, [via Meson compilation and all the `gstreamer-full-static` stuff](https://github.com/GStreamer/gstreamer/blob/be6eba3e9e792dd5c64d3ffdbf444ebef70ac87a/meson.build#L381-L412). Is it possible for me to load filesink statically? It seems like there'd need to be some kind of implementation of `gst_element_register_gofilesink` and `gst_plugin_gofilesink_register`, if I'm understanding that correctly? Happy to do what it takes to make this work if someone can point me in the right direction.

**Comment by ArtemMartus** [comment]
Sounds like an interesting topic to investigate. Look at https://forum.golangbridge.org/t/how-to-build-with-golang-archive/27331/7  go buildmode c-archive. That has to produce you a static .a archive that theoretically can be linked with any other project. If you build c-shared - the go tool will generate a header file with plugin registration exported function - you can use that one. Then, statically linked plugin you can register it with a nil registry.
Looking forward to your results!

**Comment by RSWilli** [comment]
I'm currently on vacation, but the example you are mentioning was created by @tinyzimmer 

From what I understand about the `gstreamer-full-static` build (I want to play around with it in the future) the generated c shared file must be in the correct auto discoverable directory before creating the full static build. Also you need to configure the plugin to be included in the build.

However if you want to use the go-gst element in a golang application there is a simpler way: just call the register function after `gst.Init`. This registers the element in the factories which afterwards can be used with `gst.NewElement` etc. Since the register function is go code the static linking should be trivially done via the go linker flags

**Comment by iameli-streams** [comment]
> However if you want to use the go-gst element in a golang application there is a simpler way: just call the register function after `gst.Init`. This registers the element in the factories which afterwards can be used with `gst.NewElement` etc. Since the register function is go code the static linking should be trivially done via the go linker flags

Awesome, this sounds like it will definitely work for me. Giving it a try now. After I do that, I should be able to use it in pipelines via `gst.NewPipelineFromString` and such?

**Comment by iameli-streams** [comment]
Documenting my attempts here... I'm using `gofilesink` unmodified from [here](https://github.com/go-gst/go-gst/blob/7bc995c4f5783470255577bdd9c1c888989f486c/examples/plugins/gofilesink/filesink.go), except I changed the package to `gofilesink` from `main` so I can import it.

### Attempt 1
I modified the generated `zzgenerated_plugin.go` file to export its `PluginMeta` struct (and to have `package gofilesink` instead of `main`, so now it looks like this:
```go
// !WARNING!    THIS FILE WAS GENERATED BY GST-PLUGIN-GEN    !WARNING! //
package gofilesink

import "C"

import (
	"unsafe"

	"github.com/go-gst/go-gst/gst"
	"github.com/go-gst/go-gst/gst/base"
)

// The metadata for this plugin
var PluginMeta = &gst.PluginMetadata{
	MajorVersion: gst.VersionMajor,
	MinorVersion: gst.VersionMinor,
	Name:         "gofilesink",
	Description:  "File plugins written in go",
	Version:      "v0.0.1",
	License:      gst.LicenseLGPL,
	Source:       "go-gst",
	Package:      "examples",
	Origin:       "https://github.com/go-gst/go-gst",
	ReleaseDate:  "2021-01-04",
	// The init function is called to register elements provided by the plugin.
	Init: func(plugin *gst.Plugin) bool {
		return gst.RegisterElement(
			plugin,
			// The name of the element
			"gofilesink",
			// The rank of the element
			gst.RankNone,
			// The GoElement implementation for the element
			&FileSink{},
			// The base subclass this element extends
			base.ExtendsBaseSink,
			// The interfaces this element implements
			gst.InterfaceURIHandler,
		)
	},
}

// A single method must be exported from the compiled library that provides for GStreamer
// to fetch the description and init function for this plugin. The name of the method
// must match the format gst_plugin_NAME_get_desc, where NAME is the name of the compiled
// artifact with or without the "libgst" prefix and hyphens are replaced with underscores.

//export gst_plugin_gofilesink_get_desc
func gst_plugin_gofilesink_get_desc() unsafe.Pointer { return PluginMeta.Export() }
```

And I'm using that function elsewhere in the program like this:
```go
func init() {
	gst.Init(nil)
	gst.RegisterPlugin(gofilesink.PluginMeta, gofilesink.PluginMeta.Init)
}
```

That resulted in this panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104b22314]

goroutine 1 [running]:
github.com/go-gst/go-glib/glib.goInterfaceInit(0x6000026a0030, 0x140000021c0?)
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-glib@v1.2.1/glib/go_object_exports.go:79 +0x74
github.com/go-gst/go-gst/gst._Cfunc_gst_element_register(0x151a040a0, 0x600002a98070, 0x0, 0x6000006a0080)
	_cgo_gotypes.go:7822 +0x34
github.com/go-gst/go-gst/gst.RegisterElement.func1(0x151a040a0, {0x10579ec8f, 0xa}, 0x0, {0x107c8a6c0, 0x1400039f460}, {0x107c8eb88, 0x109618aa0}, {0x140002a19e8, 0x1, ...})
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-gst@v1.2.1/gst/gst_element.go:120 +0xd8
github.com/go-gst/go-gst/gst.RegisterElement(0x8?, {0x10579ec8f?, 0xa?}, 0x0?, {0x107c8a6c0?, 0x1400039f460?}, {0x107c8eb88?, 0x109618aa0?}, {0x140002a19e8?, 0x1?, ...})
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-gst@v1.2.1/gst/gst_element.go:120 +0x98
aquareum.tv/aquareum/pkg/media/gofilesink.init.func1(0x1400007e5e8)
	/Users/iameli/code/aquareum/pkg/media/gofilesink/zzgenerated_plugin.go:27 +0x84
github.com/go-gst/go-gst/gst.goPluginInit(0x151a040a0, 0x140000021c0?)
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-gst@v1.2.1/gst/cgo_exports.go:238 +0x140
github.com/go-gst/go-gst/gst._Cfunc_gst_plugin_register_static_full(0x1, 0x19, 0x600002a98010, 0x6000028a40e0, 0x1050c787c, 0x600002a98020, 0x600002a98030, 0x600002a98040, 0x600002a98050, 0x6000026a0000, ...)
	_cgo_gotypes.go:12403 +0x34
github.com/go-gst/go-gst/gst.RegisterPlugin.func2(0x107a9a8e0?, 0x600002a98010, 0x6000028a40e0, 0x600002a98020, 0x600002a98030, 0x600002a98040, 0x600002a98050, 0x6000026a0000, 0x600002a98060)
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-gst@v1.2.1/gst/gst_plugin.go:151 +0xc8
github.com/go-gst/go-gst/gst.RegisterPlugin(0x1084ded20, 0x107c7a6d8)
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-gst@v1.2.1/gst/gst_plugin.go:151 +0x160
aquareum.tv/aquareum/pkg/media.init.0()
	/Users/iameli/code/aquareum/pkg/media/gstreamer.go:23 +0x30
fish: Job 1, './bin/aquareum' terminated by signal SIGABRT (Abort)
```

### Attempt 2
Registering the element directly: this is just me copying the element registration code directly from the `zzgenerated_plugin.go` file:
```go
func init() {
	gst.Init(nil)
	ok := gst.RegisterElement(
		nil,
		// The name of the element
		"gofilesink",
		// The rank of the element
		gst.RankNone,
		// The GoElement implementation for the element
		&gofilesink.FileSink{},
		// The base subclass this element extends
		base.ExtendsBaseSink,
		// The interfaces this element implements
		gst.InterfaceURIHandler,
	)
	if !ok {
		panic("gofilesink registration failed")
	}
}
```
That's resulting in:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x106486314]

goroutine 1 [running]:
github.com/go-gst/go-glib/glib.goInterfaceInit(0x600003cd2520, 0x140000021c0?)
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-glib@v1.2.1/glib/go_object_exports.go:79 +0x74
github.com/go-gst/go-gst/gst._Cfunc_gst_element_register(0x0, 0x6000030c8740, 0x0, 0x600001cdce00)
	_cgo_gotypes.go:7822 +0x34
github.com/go-gst/go-gst/gst.RegisterElement.func1(0x0, {0x107102951, 0xa}, 0x0, {0x1095ed500, 0x14000114a10}, {0x1095f2908, 0x10af7c860}, {0x14000143df8, 0x1, ...})
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-gst@v1.2.1/gst/gst_element.go:120 +0xd8
github.com/go-gst/go-gst/gst.RegisterElement(0x10713dcfb?, {0x107102951?, 0x10713e9e2?}, 0x46?, {0x1095ed500?, 0x14000114a10?}, {0x1095f2908?, 0x10af7c860?}, {0x14000143df8?, 0x1?, ...})
	/Users/iameli/code/go/pkg/mod/github.com/go-gst/go-gst@v1.2.1/gst/gst_element.go:120 +0x98
aquareum.tv/aquareum/pkg/media.init.0()
	/Users/iameli/code/aquareum/pkg/media/gstreamer.go:24 +0x88
fish: Job 1, './bin/aquareum' terminated by signal SIGABRT (Abort)
```

**Comment by RSWilli** [comment]
Attempt 2 is the way I do it, although I cannot see what you did wrong.

**Comment by RSWilli** [comment]
Also make sure you are using the most up to date go-gst version, the examples are not regularly updated.

**Comment by iameli-streams** [comment]
Ah, confirmed it was https://github.com/go-gst/go-glib/pull/16 causing my problems, updating to v1.3.0 got it working!
