### ISSUE TITLE
A questions regarding memory leaks

### ISSUE THREAD

**Issue by neilyoung** [go-gst/go-gst#138]
I'm wondering if I need to do more than just `pipeline.SetState(gst.StateNull)` in order to release all the memory allocated in pipelines like this (partially shown)

```

			nvstreammux
					name=mux
					batch-size=1
					width=1280
					height=720
					attach-sys-ts=0 
					nvbuf-memory-type=3 !
				nvinfer
					config-file-path=config.ini !
...
				rtspclientsink
					location=rtsp://destination
				uridecodebin
					name=source
					uri=rtsp://source !
				mux.sink_0
```

I'm asking because I can see, that my GOLANG app is retaining a whole lot of memory (in GB range), when running such a pipeline, and also after stopping it with the a.m. command.

In contrary the entire memory is released, when the app terminates.

Same btw. when the pipeline is run on console level using "gst-launch-1.0" and stopping it by CTRL-C. No memory leaks.

**Comment by RSWilli** [comment]
@neilyoung since golang does not have weak pointers, some signal handlers / pad probes may contain a pointer to the objects, which prevents them from beeing garbage collected. If you are using these, you'll need to disconnect them before dropping all references.

See https://github.com/go-gst/go-gst/issues/49#issuecomment-1775398312

**Comment by neilyoung** [comment]
@RSWilli Well, I'm using pad probes and surely also signal handlers. Is there a list of objects, which need to be released/disconnected or a general rule (if this, than that)?

Other than that I doubt that these can cause the allocations of several GB. Since I'm dealing with NVIDIA plugins, I believe, all these "lib****" retain the memory until killed finally. At least this is what I observe.

**Comment by RSWilli** [comment]
It's sadly not the objects, but callback `func()` that retain the references. If you step into one of the functions you are calling to attach the callback (Probe / Signal), then you can expand the function to see all the places it references.

The way pad probes and signals are (and sadly have to be) implemented in go-gst/go-glib create a strong reference in a global map via `cgo.Handle`

**Comment by RSWilli** [comment]
Hopefully this can change with weak pointers in the future, but we'll have to see.

**Comment by neilyoung** [comment]
I checked my code and found that I'm calling `RemoveProbe` once I no longer need it. Is that sufficient?

```

		i.sourcePadProbeId = sourcePad.AddProbe(gst.PadProbeTypeBuffer, i.sgie1FaceProbe)

...

		i.sourcePad.RemoveProbe(i.sourcePadProbeId)
```

**Comment by RSWilli** [comment]
> I checked my code and found that I'm calling `RemoveProbe` once I no longer need it. Is that sufficient?

Yes. Signals have a corresponding `HandlerDisconnect` (or similar)

**Comment by neilyoung** [comment]
Not sure if I use signals. Do you mean bus signals?

**Comment by RSWilli** [comment]
Signal handlers are attached via Connect and common signals include pad-added, child-added, etc
