### ISSUE TITLE
Memory leak on call to gst_tag_list_to_string

### ISSUE THREAD

**Issue by RahkVaur** [go-gst/go-gst#145]
---
name: Memory leak found on go-gst
about: Memory leak on call to gst_tag_list_to_string
labels: bug
assignees: ''

---

**What are you trying to do?**
We are using go-gst library to create some pipelines to download images from a HTTP server. Each time we want to download a new image, we create one of these pipelines to download the media, and then after using it we delete it. We observed a memory increase while executing our program and we saw that it was a call to gstreamer function gst_tag_list_to_string. We used Valgrind and confirmed that indeed there was a memory leak.

We looked for it in our code and couldn't find a single reference, so we looked for it in go-gst. We saw that there was a call from the struct TagList inside the function String(). We thought that maybe the tag list created was not being unreferenced, so we modified the code to make a deferred free of the tag list structure. When we tried the code again with Valgrind we saw that the memory leak was gone.

Our pipeline contains:

souphttpsrc ! qtdemux ! h265parse ! avdec_h265 ! videoconvert ! appsink

Valgrind report with current go-gst code (memory leak):
![image](https://github.com/user-attachments/assets/2fe61960-20d3-4c81-80d5-b79df573e0b3)

Valgrind report with go-gst code freeing memory (no memory leak):
![image](https://github.com/user-attachments/assets/b6e1770b-cfa3-4a81-9670-be45cd328bd5)

The code we are using right now for the String() function from the TagList struct:

```go
func (t *TagList) String() string {
	cStr := C.gst_tag_list_to_string(t.Instance())
	defer C.g_free((C.gpointer)(unsafe.Pointer(cStr)))
	return C.GoString(cStr)
}
```

Please, don't hesitate to ask for more information if needed, we are happy to help with anything we can!

**Comment by RSWilli** [comment]
That looks correct, since the result is `transfer:full` https://gstreamer.freedesktop.org/documentation/gstreamer/gsttaglist.html?gi-language=c#gst_tag_list_to_string

I'd appreciate a PR :)

**Comment by RahkVaur** [comment]
Thanks for your quick response! I've created the PR from the fork I created
