### ISSUE TITLE
Can't get `appsrc` to play nice with `compositor`

### ISSUE THREAD

**Issue by iameli-streams** [go-gst/go-gst#148]
I'm having trouble using raw video `appsrc` stuff with a `compositor`. Here's a small change to `examples/appsrc/main.go`, which should put a no-op compositor in the middle between everything:
```diff
diff --git a/examples/appsrc/main.go b/examples/appsrc/main.go
index 4dda389..3bf71f7 100644
--- a/examples/appsrc/main.go
+++ b/examples/appsrc/main.go
@@ -27,7 +27,7 @@ func createPipeline() (*gst.Pipeline, error) {
        }
 
        // Create the elements
-       elems, err := gst.NewElementMany("appsrc", "videoconvert", "autovideosink")
+       elems, err := gst.NewElementMany("appsrc", "compositor", "videoconvert", "autovideosink")
        if err != nil {
                return nil, err
        }
```

That results in the following:
```
▶ go build main.go && ./main
Producing frame: 0
Producing frame: 1
**
GStreamer-Video:ERROR:../gst-libs/gst/video/gstvideoaggregator.c:2633:gst_video_aggregator_sink_event: assertion failed: (seg.format == GST_FORMAT_TIME)
Bail out! GStreamer-Video:ERROR:../gst-libs/gst/video/gstvideoaggregator.c:2633:gst_video_aggregator_sink_event: assertion failed: (seg.format == GST_FORMAT_TIME)
fish: Job 1, './main' terminated by signal SIGABRT (Abort)
```

No amount of `videoconvert` before or after compositor seems to help the situation. Any ideas?

**Comment by iameli-streams** [comment]
The `SIGABRT` would indicate that a segfault did occur, no?

**Comment by RSWilli** [comment]
a segmentation fault is determined by the `SIGSEGV` signal. See also https://stackoverflow.com/questions/3413166/when-does-a-process-get-sigabrt-signal-6

I haven't used `appsrc` myself, I cannot help you sadly. From the error message though it seems that something in the pipeline expects a different segment format than you are sending.

See also https://gstreamer.freedesktop.org/documentation/additional/design/segments.html?gi-language=c

and feel free to ask follow up questions at the locations linked above.
