### ISSUE TITLE
could not determine kind of name for C.gst_debug_message_get_id

### ISSUE THREAD

**Issue by neilyoung** [go-gst/go-gst#149]
I'm running into this problem while attempting to compile an app using gst go 1.3.0 on a Raspberry PI, Bullseye.

Go version is go1.23.3 linux/arm64

GStreamer is a source installation of 1.20.0

```
../go/pkg/mod/github.com/go-gst/go-gst@v1.3.0/gst/gst_debug.go:221:20: could not determine kind of name for C.gst_debug_message_get_id
```

Cross compilation on Mac didn't work either. 

Any pointer?

**Comment by neilyoung** [comment]
I was able to work around by patching this https://github.com/go-gst/go-gst/blob/77c0c3181b018b0b7848a4247d729aa65167a7d6/gst/gst_debug.go#L221 to `return ""`.

**Comment by RSWilli** [comment]
[gst_debug_message_get_id](https://gstreamer.freedesktop.org/documentation/gstreamer/gstinfo.html?gi-language=c#gst_debug_message_get_id) is part of gstreamer as of 1.22. Please update your gstreamer installation
