### ISSUE TITLE
Get rms from plugin level (Type GValueArray-gdouble)

### ISSUE THREAD

**Issue by db-tech** [go-gst/go-gst#15]
Hi, I am trying to implement a silence detection with gstreamer and wanted to use the level plugin.
When the plugin sends a message, the structure should contain a property "rms" which is GValueArray of type gdouble.

Is there a way to retrieve this value ?

https://gstreamer.freedesktop.org/documentation/level/index.html?gi-language=c

**Comment by RSWilli** [comment]
Disclaimer: I haven't used this particular plugin.

In theory the following should be possible (from what I understand from the code snippet on the docs you linked):
1. attach listen to the Bus on the pipeline (se [Quickstart](https://github.com/go-gst/go-gst#quickstart))
2. convert the message to a structure (analogous to `gst_message_get_structure`) 
3. read the structure's `rms` property as a `glib.Value`
4. cast the returned GValue to a [ValueArrayValue](https://github.com/go-gst/go-gst/blob/main/gst/gst_values.go#L566)

Bindings for the needed types exist, although I'm not sure if all bindings needed for your use case are bound.

It sounds like something the bindings can do already, and if something is missing this should be an easy addition.

**Comment by RSWilli** [comment]
It seems like we do not have a binding for the needed [`gst_message_get_structure`](https://gstreamer.freedesktop.org/documentation/gstreamer/gstmessage.html?gi-language=c#gst_message_get_structure)

Feel free to send a PR though.
