### ISSUE TITLE
How to write custom elements

### ISSUE THREAD

**Issue by RSWilli** [go-gst/go-gst#19]
we need an official documentation for how to create custom `gstElements` in go.

Essentially https://tinyzimmer.github.io/posts/exporting-gobject-from-go/ but maybe more dense?

We already have https://github.com/go-gst/go-gst/tree/main/examples/plugins but with very little documentation

**Comment by RSWilli** [comment]
@tinyzimmer do you have an example of how to use [`BinImpl`](https://github.com/go-gst/go-gst/blob/main/gst/gst_bin_impl.go) through the bindings?

**Comment by tinyzimmer** [comment]
Ho boy. Yea probably. Examples are likely littered across various small projects that I may or may not still have. Will do some digging.

Documentation is best found inline probably. For example if you look more closely at the example file source you'll find some better explanations. (Not ideal I know :stuck_out_tongue: ) https://github.com/go-gst/go-gst/blob/main/examples/plugins/gofilesrc/filesrc.go.

I'll report back with any other examples I find.

**Comment by RSWilli** [comment]
In another issue you said:

> Ah well then we can probably assume that wherever I said plugins, I intended to say elements

I just found out that we currently do have support for plugins, not only custom elements.

for clarification:

* a custom element is an extension of a GObject that can be inserted in the pipeline. This is useful e.g. to combine multiple elements in a bin that "just works"
* a plugin requires pluginmetadata and the stuff that gst-plugin-gen creates

The gst-plugin-gen can save us some work, but it's output is not worth the magic. I would rather drop support for the go generate and add a boilerplate for how to do basic plugins.

**Comment by RSWilli** [comment]
e.g. for your gofilesrc the output is only:

```go
// !WARNING!    THIS FILE WAS GENERATED BY GST-PLUGIN-GEN    !WARNING! //
package main

import "C"

import (
	"unsafe"

	"github.com/go-gst/go-gst/gst"
	"github.com/go-gst/go-gst/gst/base"
)

// The metadata for this plugin
var pluginMeta = &gst.PluginMetadata{
	MajorVersion: gst.VersionMajor,
	MinorVersion: gst.VersionMinor,
	Name:         "gofilesrc",
	Description:  "File plugins written in go",
	Version:      "v0.0.1",
	License:      gst.LicenseLGPL,
	Source:       "go-gst",
	Package:      "examples",
	Origin:       "https://github.com/go-gst/go-gst",
	ReleaseDate:  "2021-01-04",
	// The init function is called to register elements provided by the plugin.
	Init: func(plugin *gst.Plugin) bool {
		return gst.RegisterElement(
			plugin,
			// The name of the element
			"gofilesrc",
			// The rank of the element
			gst.RankNone,
			// The GoElement implementation for the element
			&FileSrc{},
			// The base subclass this element extends
			base.ExtendsBaseSrc,
			// The interfaces this element implements
			gst.InterfaceURIHandler,
		)
	},
}

// A single method must be exported from the compiled library that provides for GStreamer
// to fetch the description and init function for this plugin. The name of the method
// must match the format gst_plugin_NAME_get_desc, where NAME is the name of the compiled
// artifact with or without the "libgst" prefix and hyphens are replaced with underscores.

//export gst_plugin_gofilesrc_get_desc
func gst_plugin_gofilesrc_get_desc() unsafe.Pointer { return pluginMeta.Export() }
```

which is small enough that I would expect a developer to be able to fill it out by themselves

**Comment by tinyzimmer** [comment]
Yea I see no problem with that. As long as it's well documented on how to do it. The original intention behind the generator was entirely from a "developer experience" perspective. 

More specifically, I liked the idea of the developer not having to import "C" or "unsafe" in the code they were writing, but it was practically unavoidable in that necessary boilerplate to register with the type system and all that.

**Comment by RSWilli** [comment]
I think that it is acceptable to import C when you want to create a plugin that can be called from C.

For custom elements though that should be avoided, which it is from what I can see.

**Comment by RSWilli** [comment]
> I just found out that we currently do have support for plugins, not only custom elements.

In fact we do ONLY have support for plugins and not for custom elements, since the gst.RegisterElement requires a plugin to be passed.

**Comment by sdroege** [comment]
You don't need to register elements to use them (can just use their constructor), and you can pass `NULL` as plugin to `gst_element_register()` (but maybe that's currently unsupported in the bindings)

**Comment by tinyzimmer** [comment]
I can't remember fully, but I think whole idea of the factory at the time was exposing a "go-like" interface to getting to `gst_element_register()` with as few exported C calls as possible.

I'm sure there are other ways to get to that point. The cleanliness from a user perspective would probably be subjective.

**Comment by tinyzimmer** [comment]
I mean yea. Now that I'm thinking about it again that was pretty much the whole idea. And what led down the rabbit hole that became that blog post.

The problem of how to get GObject to be happy with a Go Object. If we can find a clean way to pass the custom subclassing and all that directly to `get_element_register()` without having to go through the plugin system, then that would definitely be awesome and we should do that.

The factory however only becomes an extremely small step from there regardless. So I think at that point it would make sense to keep both. But I'm open to discussion on that.

**Comment by RSWilli** [comment]
> but maybe that's currently unsupported in the bindings

It is, see here: https://github.com/go-gst/go-gst/blob/main/gst/gst_element.go#L108 this panics

**Comment by RSWilli** [comment]
I'm currently also looking at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/main/tutorial/src/progressbin/imp.rs for reference, and I cannot figure out how I am supposed to create the pads from the PadTemplates.

**Comment by tinyzimmer** [comment]
What we effectively need in order to keep this support is the ability to take one or more Go methods, turn them into a `GstElement` that we can pass to gstreamer core, and have those methods be called at the appropriate times. Additionally, those methods need to be correctly tied to any other elements or objects they create. Garbage collected appropriately, and so on. Since gstreamer relies entirely on the GObject type system, that became a lot harder than just passing trampolines around.

We may come full circle and say, "well the only way to do that is the hacky custom glib code that creates a plugin currently". If that ends up being the case we may end up choosing to revisit the underlying decision to try to keep this support. Or we can also still try to just grab the tidbits necessary and throw them in a separate package.

**Comment by RSWilli** [comment]
@tinyzimmer I think it could work fine the way it is currently. I'm just struggling with the documentation and the "what do I need to implement"

@sdroege can you take a look at this code: https://github.com/go-gst/go-glib/blob/main/glib/go_object.go#L15-L27 what this effectively does is call the subclasses constructed before the parent's

**Comment by RSWilli** [comment]
Props to past @tinyzimmer :

There is a `ToGstBin` function to cast the passed object to a bin, with #58 it even works with element factories. The switch in https://github.com/go-gst/go-glib/blob/main/glib/go_object.go#L15-L27 doesn't seem to make a difference though.

```go
func (ice *icecastOutput) Constructed(o *glib.Object) {
	b := gst.ToGstBin(o)

	b.Add(ice.oggmux)
}
```

![image](https://github.com/go-gst/go-gst/assets/18500203/ab0ca067-06c6-4ab4-b131-712b8a82d3a6)

I'll work my way through it and add an example for the custom bin if I find the time

**Comment by RSWilli** [comment]
The only thing I'm missing currently is how do I get access to the class in the `New` method. Is it possible to get the parent class of a `GoObjectSubclass`?

**Comment by RSWilli** [comment]
It turns out `New` is not the correct method to do this. There also is a `InstanceInit` function that receives the actual `glib.Object` where one has access to the class

```go
func (ice *icecastOutput) InstanceInit(instance *glib.Object) {
	ice.oggmux, _ = gst.NewElement("oggmux")

	ice.flacenc, _ = gst.NewElementWithProperties("flacenc", map[string]interface{}{
		"quality":     0,
		"seekpoints":  0,
		"hard-resync": true,
	})

	klass := instance.Class()

	class := gst.ToElementClass(klass)

	ice.srcpad = gst.NewGhostPadNoTargetFromTemplate("sink", class.GetPadTemplate("sink"))
}
```

![image](https://github.com/go-gst/go-gst/assets/18500203/895c4ba5-f149-4701-bcdc-88253351fadd)

**Comment by sdroege** [comment]
> @sdroege can you take a look at this code: https://github.com/go-gst/go-glib/blob/main/glib/go_object.go#L15-L27 what this effectively does is call the subclasses constructed before the parent's. Is that correct since it differs in the rust code?

It usually doesn't matter but for this one it's better to call the parent first. It depends on the virtual method in question.

**Comment by atishnazir** [comment]
@RSWilli I was constructing a Bin this week, here were the interfaces I implemented:

```
type example struct {
	settings *exampleSettings
	state    *exampleState
}

var _ interface {
	glib.GoObjectSubclass
	glib.Initter
	glib.GoObject

	ChangeState(*gst.Element, gst.StateChange) gst.StateChangeReturn
} = &example{}
```

Then provided implementations for them, something like this:

```

// Create skeleton instance of class
func (ex example) New() glib.GoObjectSubclass
func (ex example) ClassInit(klass *glib.ObjectClass)

// Create your child elements and connect pads here:
func (ex example) InstanceInit(object *glib.Object) {
	bin := gst.ToGstBin(object)
	identity, _ := gst.NewElement("identity")
	_ = bin.AddMany(identity)
	
	sink := gst.NewGhostPadFromTemplate("sink", identity.GetStaticPad("sink"), sinkPadTemplate)
	src := gst.NewGhostPadFromTemplate("src", identity.GetStaticPad("src"), srcPadTemplate)
	bin.Element.AddPad(sink.Pad)
	bin.Element.AddPad(src.Pad)
}

func (ex example) SetProperty(object *glib.Object, id uint, value *glib.Value)
func (ex example) GetProperty(object *glib.Object, id uint) *glib.Value
func (ex example) Constructed(object *glib.Object)

// In my use case I reset my state machine on READY->PAUSE
func (ex example) ChangeState(element *gst.Element, stateChange gst.StateChange) gst.StateChangeReturn

```

**Comment by atishnazir** [comment]
I find myself split about by the partial overrides.  I borrowed the interface assertion trick from the Caddy webserver project.

I was really impressed by the anonymous interface technique @tinyzimmer used within go-gst.  That said in practice it feels like there's a cognitive load required to pick the right partial interfaces to implement.  Fanning out all the virtual methods of GstElement would result in 15 interfaces.

The Go gRPC bindings generator as a really neat mechanism for providing overridable implementations.  For a given service it generates an interface for the programmer to implement, but it also provides an embeddable concrete implementation with sensible defaults (usually named `UnimplementedInterfacename`).  The upside is that the user sees a very clean interface and by simply embedding the `Unimplemented...` type into their struct, they have something already ready to go.

**Comment by RSWilli** [comment]
I'm seeing some weird behavior where the string extracted from the glib.GValue is something like:

```
metadata2="\b\206'\216\345\177"
source="x\205'\216\345\177"
```

instead of the original string I put in. Did anyone else encounter this?

**Comment by RSWilli** [comment]
The result of this ist that I get the following error:

```
../gstreamer/subprojects/gstreamer/plugins/elements/gstfilesrc.c -> gst_file_src_start:553 -> error: No such file "?�"
```

**Comment by atishnazir** [comment]
Can you share your pipeline?  I'm looking at a reference counting issue right now, the issue can manifest in data corruption in strange and wonderful places.

**Comment by RSWilli** [comment]
@atishnazir I created a separate Issue for that and I can confirm that the issue doesn't happen when I use `SetProperty` on the created element instead of `MakeElementsWithProperties`

**Comment by RSWilli** [comment]
Closing this because https://github.com/go-gst/go-gst/pull/152 adds an example that creates and uses the elements in the same application.
