### ISSUE TITLE
How to set GstElement *(or *gst.Element) to a Property?

### ISSUE THREAD

**Issue by braveyao** [go-gst/go-gst#65]
It looks like cgocheck may not be the only headache?

Hi, I'm trying to utilize the "splitmuxsink" to split a streaming(which may have different format), hence need to set different muxer and an appSink elements to the "splitmuxsink". Right now failed to do so.

To show the problem clearly, I picked some relevant codes into a snippet as below:
```
package main

import (
	"fmt"

	"github.com/go-gst/go-gst/gst"
)

func gstTest() {
	gst.Init(nil)

	var sink *gst.Element
	var err error
	if sink, err = gst.NewElement("splitmuxsink"); err != nil {
		fmt.Println("failed to create splitmuxsink: ", err)
		return
	}

	if err = sink.SetProperty("async-finalize", false); err != nil {
		fmt.Println("failed to set async-finalize to splitmuxsink: ", err)
		return
	}

	var mux *gst.Element
	if mux, err = gst.NewElement("webmmux"); err != nil {
		fmt.Println("failed to create webmmux: ", err)
		return
	}

	if err = sink.SetProperty("muxer", mux); err != nil {
		fmt.Println("failed to set muxer to splitmuxsink: ", err)
		return
	}

	/*
	       var appSink *app.Sink

	   	if appSink, err = app.NewAppSink(); err != nil {
	   		fmt.Println("failed to create appSink: ", err)
	   		return
	   	}	   	
	        if err = sink.SetProperty("sink", appSink); err != nil {
		        fmt.Println("failed to set sink to splitmuxsink: ", err)
		        return
	        }
	*/
}
```

Running the above codes will get error as "panic: runtime error: cgo argument has Go pointer to unpinned Go pointer", while It seems that glib/gvalue.go already convert the go pointer to a unsafe.Pointer.
Running it with GODEBUG=cgocheck=0 will get error returned by SetProperty(), "Invalid type gpointer for property muxer", which means *gst.Element isn't equal to GstElement*?

I see in github nobody sets property of a GstElement with golang at all. So wondering how to do that?

Thanks in advance!

**Comment by RSWilli** [comment]
The runtime is right, your code gives cgo access to a go object pointer. (See https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md) Even if the pointer is cast to an `unsafe.Pointer`, it still points to the same object. This must be handled in the bindings, I'll check with the following if it has been done:

* The setting of the property is done in `go-glib` via the `gValue` function [here](https://github.com/go-gst/go-glib/blob/main/glib/gvalue.go#L237-L243)
* Each element is a wrapped `gst.Object` that wraps `glib.InitiallyUnowned` [source](https://github.com/go-gst/go-gst/blob/main/gst/gst_object.go#L13)
* `glib.InitiallyUnowned` wraps `glib.Object`[source](https://github.com/go-gst/go-glib/blob/b2d34240bcb44a1b341b2f094eb2ab33e1a2aa98/glib/glib.go#L462-L467)

@braveyao could you please debug the behavior of the `gValue` function [here](https://github.com/go-gst/go-glib/blob/main/glib/gvalue.go#L237-L243) when your issue appears?

**Comment by RSWilli** [comment]
> I see in github nobody sets property of a GstElement with golang at all. So wondering how to do that?

I personally don't need that feature, if this issue get's fixed could you create a PR with an example, please?

> gst.Element isn't equal to GstElement

No they aren't. `gst.Element` is a golang struct wrapping the C struct `GstElement` [source](https://github.com/go-gst/go-gst/blob/main/gst/gst_element.go#L47) The bindings always pass the underlying C structs to the gstreamer core, but in your case they seem to leak a go struct.

**Comment by RSWilli** [comment]
@braveyao I have a fix for this issue, it didn't concern the Setproperty but instead the GValue creation. I shrunk your test to the following, which works now

```go
package main

import (
	"github.com/go-gst/go-gst/gst"
)

func main() {
	gst.Init(nil)

	sink, _ := gst.NewElement("splitmuxsink")

	mux, _ := gst.NewElement("webmmux")

	sink.SetProperty("muxer", mux)
}
```

could you test https://github.com/go-gst/go-glib/pull/4 please inn your local setup? Add a replace directive for go-glib with the following commit hash: `dad64b7d93d60f78e43166fa10f12d2e60dcf768`

**Comment by braveyao** [comment]
Hi RSWilli@

Thanks so much for taking action on this!
Unfortunately, I think this is not completely fixed yet.

To make sure the fix involved, I synced down the [value_transformer_for_object](https://github.com/go-gst/go-glib/compare/value_transformer_for_object) ([#4](https://github.com/go-gst/go-glib/pull/4)) branch and add the replace to the local repo. By adding some logging, I'm sure your fix is effective in my local test.
Right now, running it without GODEBUG=cgocheck=0  won't cause a panic!
But if you check the return value of SetProperty() like below, there is a new error message, "Invalid type GObject for property muxer".
~~~
	if err := sink.SetProperty("muxer", mux); err != nil {
		fmt.Println("failed to set element to splitmuxsink: ", err)
	}
~~~

Regards
Brave

**Comment by RSWilli** [comment]
@braveyao do you know how one would set this in C? This would help me a lot.

**Comment by RSWilli** [comment]
ah, lets go chatgpt:

```c
#include <gst/gst.h>

int main(int argc, char *argv[]) {
    // Initialize GStreamer
    gst_init(&argc, &argv);

    // Create a GValue
    GValue element_value = G_VALUE_INIT;

    // Initialize the GValue for GstElement type
    g_value_init(&element_value, GST_TYPE_ELEMENT);

    // Now you can set the GstElement into the GValue
    GstElement *your_element = gst_element_factory_make("your_element_type", "your_element_name");
    g_value_set_object(&element_value, your_element);

    // ... Use the GValue with the GstElement as needed ...

    // Don't forget to clean up
    g_object_unref(your_element);
    g_value_unset(&element_value);

    // Cleanup GStreamer
    gst_deinit();

    return 0;
}
```

That works in go without an error, you'll stil have to test it @braveyao. It is now implemented in go-gst https://github.com/go-gst/go-gst/pull/66, I will close the PR in go-glib

**Comment by braveyao** [comment]
Hi RSWilli@, 

There is no error with go-gst [#66](https://github.com/go-gst/go-gst/pull/66) any more!
So many thanks!

**Comment by RSWilli** [comment]
done in #66

@braveyao I would appreciate it if you could contribute a simple example that demonstrates this functionality.
