### ISSUE TITLE
video display support on MacOS

### ISSUE THREAD

**Issue by andrein** [go-gst/go-gst#67]
Hello,

I've tried to use autovideosink, glimagesink and osxvideosink with go-gst but I don't see a video window anywhere. If I use gst-launch-1.0, all sinks work fine.

Is this expected?

**Comment by RSWilli** [comment]
Please add a reproduction snippet.

**Comment by andrein** [comment]
Hi @RSWilli, I can easily reproduce this using the playbin example.

```go run examples/playbin/main.go https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8```

**Comment by andrein** [comment]
It's not the compile time, I can hear the sound in the background, I just don't see a video window anywhere.

**Comment by RSWilli** [comment]
```
gst-launch-1.0 playbin uri=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8
```

when I run this, I get the following error:

```
Missing element: H.264 (High Profile) decoder
WARNING: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: No decoder available for type 'video/x-h264, stream-format=(string)avc, pixel-aspect-ratio=(fraction)1/1, width=(int)1920, height=(int)1080, framerate=(fraction)60/1, coded-picture-structure=(string)frame, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true, alignment=(string)au, profile=(string)high, level=(string)4, codec_data=(buffer)01640028ffe1001b67640028acd980780227e5c044000003000400000301e03c60c66801000668e9785cb22c'.
```

and I can hear sound for exactly 10s. I don't think that this is an issue with the go bindings (because you can hear sound), but either your setup or gstreamer itself. But such questions are better asked here: https://discourse.gstreamer.org/

**Comment by andrein** [comment]
That's odd, it works fine for me, i've watched about 10 minutes of Big Buck Bunny just now. I'm using gstreamer 1.22.9.

**Comment by RSWilli** [comment]
I was missing the h264 decoder as the error message said. On linux the example now also works fine.

Still, since you can hear sound when running the example, this is not a go-gst issue. Debugging help for specific elements is better placed in the discourse: https://discourse.gstreamer.org/

**Comment by RSWilli** [comment]
If this *is* a `go-gst` issue, then I don't see where some sinks could break on a specific system. In that case I would also need some feedback about the requirements of some specific elements.

I also do not have a MacOS machine to be able to test this issue, nor do I currently use video decoding in my applications using `go-gst`

**Comment by andrein** [comment]
I tried the examples on my wife's Intel Mac, and they work, so that ruled out go-gst. When I looked further on my machine, I noticed that I had installed gstreamer using the pkg installer while the other one was installed via homebrew. Once I removed it and installed gstreamer from homebrew the autovideosink worked on my Mac also.

Thanks for looking into this @RSWilli!
