### ISSUE TITLE
possible misuse of unsafe.Pointer in gasyncresult.go

### ISSUE THREAD

**Issue by sirzooro** [go-gst/go-gst#74]
I tried to add these bindings to my app, and during compilation I got following error:

```
compilepkg: nogo: errors found by nogo during build-time code analysis:
/.../vendor/github.com/go-gst/go-glib/glib/__main__/vendor/github.com/go-gst/go-glib/glib/gasyncresult.go:86:55: possible misuse of unsafe.Pointer (unsafeptr)
```

I was able to silence this by adding `// nolint:unsafeptr` comment to this line. Please fix this or add this comment if this is a false positive.

**Comment by RSWilli** [comment]
This is the line in question: https://github.com/go-gst/go-glib/blob/main/glib/gasyncresult.go#L86

**Comment by RSWilli** [comment]
The function in question is the following:

```go
// IsTagged is a wrapper around g_async_result_is_tagged
func (v *AsyncResult) IsTagged(sourceTag uintptr) bool {
	c := C.g_async_result_is_tagged(v.native(), C.gpointer(sourceTag))
	return gobool(c)
}
```

The linter is complaining about a cast from the `uintptr` argument to a `unsafe.Pointer` via `C.gpointer`. go vet also catches this.

Related to #62

**Comment by sirzooro** [comment]
No, feel free to change it.

**Comment by RSWilli** [comment]
FYI this issue was autoclosed and is only actually completed with the merger of #75
