### ISSUE TITLE
'get-internal-session' unable to retrieve RTPSession in 'on-ssrc-active'

### ISSUE THREAD

**Issue by yelodevopsi** [go-gst/go-gst#89]
**update**: Sorry for the many edits @RSWilli 

I've extended the base-example with a manager and `on-ssrc-active`.

Here is my pipeline. I forward an RTSP-stream towards an WHEP endpoint in MediaMTX server.
```
GST_DEBUG=4 ./pipeliner "rtspsrc location=rtsp://172.25.25.102:554/axis-media/media.amp name=src latency=15 drop-on-latency=true udp-buffer-size=10242888 ! rtph264depay ! h264parse ! rtspclientsink location=rtsp://localhost:7554/PI-10"
```

- The strange thing is that i have **the exact same code in python** which are able to retrieve the session.

- Are there any special dependencies I need when digging into rtspsrc =>rtpbin element which is not implemented in go-gst? (I'm quite new to go btw)

- I've tested the code in both Ubuntu and Windows dev-envs, and I get the same <nil> error when trying to retrieve the `get-internal-session`

```go
// This is the same as the `launch` example. See the godoc and other examples for more
// in-depth usage of the bindings.
package main

import (
	"fmt"
	"os"
	"reflect"
	"strings"

	"github.com/go-gst/go-glib/glib"
	"github.com/go-gst/go-gst/gst"
)

func main() {
	// This example expects a simple `gst-launch-1.0` string as arguments
	if len(os.Args) == 1 {
		fmt.Println("Pipeline string cannot be empty")
		os.Exit(1)
	}

	// Initialize GStreamer with the arguments passed to the program. Gstreamer
	// and the bindings will automatically pop off any handled arguments leaving
	// nothing but a pipeline string (unless other invalid args are present).
	gst.Init(&os.Args)

	// Create a main loop. This is only required when utilizing signals via the bindings.
	// In this example, the AddWatch on the pipeline bus requires iterating on the main loop.
	mainLoop := glib.NewMainLoop(glib.MainContextDefault(), false)

	// Build a pipeline string from the cli arguments
	pipelineString := strings.Join(os.Args[1:], " ")

	/// Let GStreamer create a pipeline from the parsed launch syntax on the cli.
	pipeline, err := gst.NewPipelineFromString(pipelineString)
	if err != nil {
		fmt.Println(err)
		os.Exit(2)
	}

	// Add manager to the pipeline
	srcElement, err := pipeline.GetElementByName("src")
	if err != nil {
		fmt.Println(err)
		os.Exit(2)
	}

	srcElement.Connect("new-manager", srcManager)

	// Add a message handler to the pipeline bus, printing interesting information to the console.
	pipeline.GetPipelineBus().AddWatch(func(msg *gst.Message) bool {
		switch msg.Type() {
		case gst.MessageEOS: // When end-of-stream is received flush the pipeling and stop the main loop
			pipeline.BlockSetState(gst.StateNull)
			mainLoop.Quit()
		case gst.MessageError: // Error messages are always fatal
			err := msg.ParseError()
			fmt.Println("ERROR:", err.Error())
			if debug := err.DebugString(); debug != "" {
				fmt.Println("DEBUG:", debug)
			}
			mainLoop.Quit()
		default:
			// All messages implement a Stringer. However, this is
			// typically an expensive thing to do and should be avoided.
			fmt.Println(msg)
		}
		return true
	})

	// Start the pipeline
	pipeline.SetState(gst.StatePlaying)

	// Block and iterate on the main loop
	mainLoop.Run()
}

func srcManager(element *gst.Element, manager *gst.Element) {
	fmt.Println("New manager detected:", manager)
	manager.Connect("on-ssrc-active", sourceActiveMonitorPeriodically)

}


func sourceActiveMonitorPeriodically(rtpBin *gst.Element, sessionID uint, ssrc uint32) {
    // Use reflection to determine the type of stats
    rtpBinType := reflect.TypeOf(rtpBin)
    fmt.Println("Type of rtpBin:", rtpBinType)

    fmt.Printf("Source active: sessionID: %v, ssrc: %v\n", sessionID, ssrc)

    // Debug prints for sessionID and rtpBin
    // fmt.Printf("Emitting get-internal-session for sessionID: %d\n", sessionID)
    fmt.Printf("Emitting get-session for sessionID: %d\n", sessionID)
    fmt.Printf("rtpBin: %v\n", rtpBin)

    // Get the session instance which manages the current source
    session, err := rtpBin.Emit("get-session", sessionID)
    if err != nil {
        fmt.Println("Error emitting 'get-session' signal:", err)
        fmt.Println("here is the session", session)
        return
    }

    // Get the session instance which manages the current source
    session, err := rtpBin.Emit("get-internal-session", sessionID)
    if err != nil {
        fmt.Println("Error emitting signal:", err)
        return
    }

    // Check if session is nil
    if session == nil {
        fmt.Println("Error: session is nil")
        return
    }

    fmt.Println("Session:", session)

}

```

**Comment by RSWilli** [comment]
Hi

> I get the same error

What's the error?

> Are there any special dependencies I need when digging into rtspsrc =>rtpbin element which is not implemented in go-gst? (I'm quite new to go btw)

That depends. If you want to call plugin specific functions, then you need special bindings for this. Also if the plugin requires any dependencies then you need to have them installed. For most of the "basic gstreamer stuff" there are already bindings present.

> manager.Connect("on-ssrc-active", sourceActiveMonitorPeriodically)

Are you sure that this isn't a typo?

**Comment by yelodevopsi** [comment]
I'm really sorry. This was a bad issue description. 😅 Things go fast these days: Here is the error:

![image](https://github.com/go-gst/go-gst/assets/11426361/27e5a93f-faf3-47e5-b58b-c6b3f526dc0e)

Basically I get a `<nil>` in Ubuntu or `(NULL)` in Windows. But not when using the python code below. 

Is GObjects supported in the bindings? The element i should get is this:
https://gstreamer.freedesktop.org/documentation/rtpmanager/RTPSource.html?gi-language=c

Here's the Python-equivalent code that's able to extract the RTPSession from `get-internal-session`
```python

gi.require_version("GLib", "2.0")
gi.require_version("Gst", "1.0")

....

def source_active_monitor_periodly_callback(rtpbin: Gst.Bin, session_id, ssrc):
    
    print("session_id: ", session_id, "ssrc: ", ssrc)
    if session_id is not None:
        # Get the session instance which manages the current source
        session = rtpbin.emit(
            "get-internal-session", session_id
        )  # GObject.Object -> RTPSession
        
        print(session)

        # Get all stats of current source
        if session is not None:
            # Get current source by its identifier
            source = session.emit(
                "get-source-by-ssrc", ssrc
            )  # GObject.Object -> RTPSource

            # Get all stats of the source pipeline
            stats: Gst.Structure = source.get_property("stats")

            print(" ** RTPSource stats")

            print(f"  packets-lost: {stats.get_value('packets-lost')}")
            print(f"  packets-receivedt: {stats.get_value('packets-received')}")

```

**Comment by RSWilli** [comment]
> Is GObjects supported in the bindings?

Yes, GObject is wrapped by `glib.Object`.

Personally I have not looked into `Emit()` and how to use it, but I wonder why the signals you are emitting in the python code differ from in the go code. Is this correct?

**Comment by yelodevopsi** [comment]
> Personally I have not looked into `Emit()` and how to use it, but I wonder why the signals you are emitting in the python code differ from in the go code. Is this correct?

Ah! Sorry for the confusion:

* I've attached the python-code with  `get-internal-session` which are able to fill the `session` variable.
* In the Go-code above I've tested both `get-internal-session` and `get-session` to check if I get any session at all - but I get only `nil`, which I don't with python.

**Comment by yelodevopsi** [comment]
Maybe I've not read the docs properly...? 

Do I need to create the types when using the `Emit()` handler?

```go
// Emit is a wrapper around g_signal_emitv() and emits the signal specified by the string s to an Object. Arguments to
// callback functions connected to this signal must be specified in args. Emit() returns an interface{} which must be
// type asserted as the Go equivalent type to the return value for native C callback.
//
// Note that this code is unsafe in that the types of values in args are not checked against whether they are suitable
// for the callback.
func (e *Element) Emit(signal string, args ...interface{}) (interface{}, error) {
	// We are wrapping this for the same reason as Connect.
	if e.TypeFromInstance() != glib.Type(C.GST_TYPE_ELEMENT) {
		glib.RegisterGValueMarshalers([]glib.TypeMarshaler{{T: e.TypeFromInstance(), F: marshalElement}})
	}
	return e.Object.Emit(signal, args...)
}
```

**Comment by RSWilli** [comment]
Not completely sure about this, but [the implementation](https://github.com/go-gst/go-glib/blob/main/glib/gobject.go#L302) uses `g_signal_emitv` to receive the object as a GValue instead of a raw pointer. Before returning the `GoValue()` function is called on the value, which does some reflection internally to get a go type.

AFAIK The docs are trying to warn you that the returned type is `any`/`interface{}` which means you need to type cast like you normally would in go.

-------

Since your emit tries to return a `# GObject.Object -> RTPSource`, maybe the `GoValue` function is incomplete. Could you debug into the function and check if the GObject case is properly handled?

Otherwise try to create a reproduction please that I can easily run without any additional setup. I will look into this when I have some more time available.
