### ISSUE TITLE
Go minimum version downgrade

### ISSUE THREAD

**Issue by aet** [go-gst/go-gst#90]
From https://go.dev/doc/modules/gomod-ref

```
The go directive sets the minimum version of Go required to use this module. Before Go 1.21, the directive was advisory only; now it is a mandatory requirement: Go toolchains refuse to use modules declaring newer Go versions.
```

I don't think there's anything in go-glib or go-gst that sets a hard requirement to 1.22, could you consider downgrading this down to 1.21 or even 1.20? Outside of special cases, we're mostly using 1.21 atm and some 3rdparty libraries are still having hard times with 1.22 compatibility.

Meanwhile while waiting for 1.22 components to stabilize, a fork is always an option but might as well ask! Thanks

**Comment by RSWilli** [comment]
To clarify:

Was this changed so that your module needs to clarify 1.22 in its go.mod to be able to use this module? I always thought that you just need 1.22 installed and be using it for your go build. IMO the module you are writing does not need to declare 1.22. to be compile-able by a 1.22 compiler.

> Meanwhile while waiting for 1.22 components to stabilize

1.22 is the latest stable release of golang: https://go.dev/doc/devel/release

**Comment by aet** [comment]
The problem is that as soon as people type `go mod tidy`, the latest go versions start quickly enforcing everyone to upgrade to latest one, potentially without a valid reason. Of course the most popular packages out there try not to enforce the latest and greatest all too quickly to avoid outcry.

So the problem is that if I switch from `tinyzimmer/go-gst` to `go-gst/go-gst` you need to update to latest and greatest, even if there doesn't seem to be any technical requirement for it.

**Comment by RSWilli** [comment]
I thought about this for a while, and I must decline this issue for several reasons:

* golang has a promise of campatibility (https://go.dev/doc/go1compat), so upgrading the compiler isn't a big deal
* golang even provides a simple way OOB to manage multiple go versions. https://go.dev/doc/manage-install
* the go-gst and go-glib libraries are heavily tested by myself in production, I cannot say that for older go versions.
* each new golang version includes optimizations of the compiler and runtime, which I like to take advantage of
