### ISSUE TITLE
clock code how to use go-gst 

### ISSUE THREAD

**Issue by joyhope** [go-gst/go-gst#92]
I have this code:

    GstClock *clock = gst_system_clock_obtain();
    g_object_set(clock, "clock-type", GST_CLOCK_TYPE_REALTIME, NULL);
...
    gst_pipeline_use_clock(GST_PIPELINE_CAST(renderer->pipeline), clock);

How to setup in go-gst.

**Comment by joyhope** [comment]
I tried
	clock:=gst.ObtainSystemClock()
	clock.SetArg("clock-type", "0")
	pipeline.ForceClock(clock.Clock)

It passes compile, but pipeline runtime error.  I am not sure there this code is the correct meaning of the C code.

**Comment by joyhope** [comment]
similar problem:  
the pipeline: appsink sync=false, I use code to set up the properties. 

	sink := app.SinkFromElement(elems[4])
	sink.SetSync(false)

But it does not work, 

 GStreamer-Base-CRITICAL **: 22:47:15.893: gst_base_sink_set_sync: assertion 'GST_IS_BASE_SINK (sink)' failed

**Comment by joyhope** [comment]
sysclock:=gst.ObtainSystemClock()
..
	pipeline.ForceClock(sysclock.Clock)

but: g_object_set(clock, "clock-type", GST_CLOCK_TYPE_REALTIME, NULL);
 
I could not find proper go-gst to setup.

**Comment by RSWilli** [comment]
> GStreamer-Base-CRITICAL **: 22:47:15.893: gst_base_sink_set_sync: assertion 'GST_IS_BASE_SINK (sink)' failed

This tells me that the element you are trying to set sync is not an appsink.

```
 clock.SetArg("clock-type", "0")
```

This can work, I don't know how it handles enums though. Please note there exists also `SetProperty`.

**Comment by joyhope** [comment]
It is also solved.  (The clock setup is not impact my current situation.)
